#!/bin/sh
# shfmt:

# Note - This script is intended to run in an ALPINE container.
#      - The resultant build is expected to run an an alpine based docker container.

# EG:
# docker run -i -t --rm --init -v "${PWD}:${PWD}" -w "${PWD}" alpine ./docker-build

if grep -q docker /proc/self/cgroup; then

    apk add ca-certificates gnutls-dev expat-dev sqlite-dev c-ares-dev make sed gcc g++ libc-dev

    ln -s /bin/sed /usr/bin/sed

    ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --localstatedir=/var \
        --disable-nls \
        --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt

    make -j12

    make install DESTDIR=/tmp/install
    tar cvf aria2c.tar.gz -C /tmp/install .

else
    docker run -i -t --rm --init -v "${PWD}:${PWD}" -w "${PWD}" alpine "${0}"
fi

exit 0
